project           = "cloud-run-template-naka"
region            = "asia-northeast1"
service_name      = "cloud-run-template"
github_owner      = "nakamasato"
github_repository = "cloud-run-app-template"
