project                = "cloud-run-template-naka"
region                 = "asia-northeast1"
service_name           = "cloud-run-app-sample"
github_owner           = "nakamasato"
github_repository      = "cloud-run-app-sample"
github_actions_sa_name = "ga-cloud-run-app-sample"
gh_oidc_pool_id        = "ga-cloud-run-app-sample"
gh_oidc_provider_id    = "ga-cloud-run-app-sample"
